name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      
      - name: Build iOS Framework
        run: ./gradlew :shared:linkDebugFrameworkIosX64
      
      - name: Run iOS Tests
        run: |
          cd iosApp
          xcodebuild test \
            -workspace CarFast.xcworkspace \
            -scheme CarFast \
            -destination 'platform=iOS Simulator,name=iPhone 14'
